import React, { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import AppLayout from '@components/AppLayout';
import Postzone from '@components/main/Postzone';
import Category from '@components/main/Category';
import BannerItem from '@components/main/BannerItem';
import Pagination from '@components/main/Pagination';
import WriteModal from '@components/writeModal/WriteModal';
import DetailModal from '@components/detailModal/DetailModal';
import { openModal } from '@lib/ModalUtil';
import { Button } from 'antd';
const Home: NextPage = () => {
  const [writeModalState, setWriteModalState] = useState(false);
  const [detailModalState, setDetailModalState] = useState(false);
  return (
    <>
      <React.StrictMode>
        {detailModalState && <DetailModal setDetailModalState={setDetailModalState} />}
        {writeModalState && <WriteModal setWriteModalState={setWriteModalState} />}
        <Head>
          <title>MetaverseStation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppLayout>
          <>
            <BannerItem />
            <Category />
            <Postzone setDetailModalState={setDetailModalState} />
            <BottomWrapper>
              <Pagination />
              <StyledButton onClick={() => openModal(setWriteModalState)}>글쓰기</StyledButton>
            </BottomWrapper>
          </>
        </AppLayout>
      </React.StrictMode>
    </>
  );
};

export default Home;

const BottomWrapper = styled.div`
  position: relative;
`;

const StyledButton = styled(Button)`
  position: absolute;
  right: 10px;
  top: 45px;
`;
