import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import AppLayout from '@components/AppLayout';
import Postzone from '@components/main/Postzone';
import Category from '@components/main/Category';
import BannerItem from '@components/main/BannerItem';
import Pagination from '@components/main/Pagination';
import WriteModal from '@components/writeModal/WriteModal';
import DetailModal from '@components/detailModal/DetailModal';
import { openModal } from '@lib/ModalUtil';
import { Button } from 'antd';
import { useAppDispatch, useAppSelector } from '@store/hook';
import Router from 'next/router';
import { loadPost } from '@actions/post';
import wrapper from '@store/configureStore';
import axios from 'axios';
import { loadMyInfo } from '@actions/user';

const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const [writeModalState, setWriteModalState] = useState(false);
  const [detailModalState, setDetailModalState] = useState(false);
  const me = useAppSelector((state) => state.userSlice.me);
  const mainPosts = useAppSelector((state) => state.postSlice.mainPosts);
  const gotoLogIn = () => {
    Router.push('/login');
  };
  useEffect(() => {
    dispatch(loadMyInfo());
  }, []);
  return (
    <>
      <React.StrictMode>
        {detailModalState && <DetailModal setDetailModalState={setDetailModalState} />}
        {writeModalState && <WriteModal setWriteModalState={setWriteModalState} />}
        <Head>
          <title>MetaverseStation</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppLayout>
          <>
            <BannerItem />
            <Category />
            <Postzone setDetailModalState={setDetailModalState} mainPosts={mainPosts} />
            <BottomWrapper>
              <Pagination />
              <StyledButton
                onClick={() => {
                  me ? openModal(setWriteModalState) : gotoLogIn();
                }}
              >
                글쓰기
              </StyledButton>
            </BottomWrapper>
          </>
        </AppLayout>
      </React.StrictMode>
    </>
  );
};

export default Home;

export const getServerSideProps = wrapper.getServerSideProps((store) => async (ctx) => {
  // SSR에서 쿠키 받아오는 방법.
  const cookies = ctx.req?.headers?.cookie;
  // 쿠키 공유 방지,
  axios.defaults.headers.Cookie = '';
  if (ctx.req && cookies) axios.defaults.headers.Cookie = cookies;

  await store.dispatch(loadPost());
  return { props: {} };
});

const BottomWrapper = styled.div`
  position: relative;
`;

const StyledButton = styled(Button)`
  position: absolute;
  right: 10px;
  top: 45px;
`;
