import React, { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';
import AppLayout from '@components/AppLayout';
import Postzone from '@components/main/Postzone';
import Category from '@components/main/Category';
import BannerItem from '@components/main/BannerItem';
import Pagination from '@components/main/Pagination';
import WriteModal from '@components/writeModal/WriteModal';
import DetailModal from '@components/detailModal/DetailModal';
import { openModal } from '@lib/ModalUtil';
import { Button } from 'antd';
import { useAppDispatch, useAppSelector } from '@store/hook';
import Router from 'next/router';
import { loadPost } from '@actions/post';
import wrapper from '@store/configureStore';
import axios from 'axios';
import { loadMyInfo } from '@actions/user';
import cookies from 'next-cookies';
import { saveAccessToken } from '@slices/userSlice';
const Home: NextPage = () => {
  const [writeModalState, setWriteModalState] = useState(false);
  const [detailModalState, setDetailModalState] = useState(false);
  const me = useAppSelector((state) => state.userSlice.me);
  const mainPosts = useAppSelector((state) => state.postSlice.mainPosts);

  const gotoLogIn = () => {
    Router.push('/login');
  };
  return (
    <>
      <Head>
        <title>MetaverseStation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {writeModalState && <WriteModal setWriteModalState={setWriteModalState} />}
      {detailModalState && <DetailModal setDetailModalState={setDetailModalState} />}

      <AppLayout>
        <>
          <BannerItem />
          <Category />
          <Postzone setDetailModalState={setDetailModalState} mainPosts={mainPosts} />
          <BottomWrapper>
            <Pagination />
            <StyledButton
              onClick={() => {
                me ? openModal(setWriteModalState) : gotoLogIn();
              }}
            >
              글쓰기
            </StyledButton>
          </BottomWrapper>
        </>
      </AppLayout>
    </>
  );
};

export default Home;

const BottomWrapper = styled.div`
  position: relative;
`;

const StyledButton = styled(Button)`
  position: absolute;
  right: 10px;
  top: 45px;
`;

export const getServerSideProps = wrapper.getServerSideProps((store) => async (ctx) => {
  const token = cookies(ctx).Token;
  token
    ? (axios.defaults.headers.common['Authorization'] = `Bearer ${token}`)
    : (axios.defaults.headers.common['Authorization'] = '');
  if (token) {
    store.dispatch(saveAccessToken(token));
  }
  await store.dispatch(loadMyInfo());
  if (store.getState().userSlice.AccessToken !== null) {
    await store.dispatch(loadPost());
  }
  return { props: {} };
});
